export interface LettersInterface {
  "A": boolean,
  "B": boolean,
  "C": boolean,
  "Č": boolean,
  "Ć": boolean,
  "D": boolean,
  "Đ": boolean,
  "E": boolean,
  "F": boolean,
  "G": boolean,
  "H": boolean,
  "I": boolean,
  "J": boolean,
  "K": boolean,
  "L": boolean,
  "M": boolean,
  "N": boolean,
  "O": boolean,
  "P": boolean,
  "R": boolean,
  "S": boolean,
  "Š": boolean,
  "T": boolean,
  "U": boolean,
  "V": boolean,
  "Z": boolean,
  "Ž": boolean,
}

export interface PlayerInterface {
  id: string,
  name: string,
  avatarId: number,
  word: string,
  lives: number,
  points: number,
  letters: LettersInterface,
  room: string,
  host: boolean,
  connected: boolean,
  done: boolean;
}

export interface RoomInterface {
  tempo: string,
  code: string,
  gamemode: string,
  difficulty: string,
  timePerTurn: number,
  startLives: number,
  maxLives: number,
  maxPoints: number,
  djIncluded: boolean,
  players: Array<PlayerInterface>,
  spectators: Array<PlayerInterface>,
  gameRunning: boolean,
  playerTurn: number,
  timer: number,
  usedAvatarIds: Array<number>
  winner: PlayerInterface | null,
  combination: string,
  usedWords: Array<string>
}